---
name: Load Parameters
description: Load parameters for the build job

outputs:
  build_matrix:
    description: Build matrix
    value: ${{ steps.set-matrix.outputs.build_matrix }}

  docker_image:
    description: Docker image
    value: ${{ steps.get-docker-image.outputs.image_name }}

  flat_build:
    description: Command to run for the flat build
    value: ${{ steps.set-build-command.outputs.flat_build }}

  sdk_build_command:
    description: Command to run for the SDK build
    value: ${{ steps.set-build-command.outputs.sdk_build_command }}

runs:
  using: "composite"
  steps:
    - name: Set Build Matrix
      id: set-matrix
      uses: actions/github-script@v7
      with:
        script: |
          const fs = require('fs');
          const path = require('path');
          const core = require('@actions/core');

          const filePath = path.join(process.env.GITHUB_WORKSPACE, 'ci', 'MACHINES.json');

          if (!fs.existsSync(filePath)) {
            core.setFailed(`MACHINES.json not found at ${filePath}`);
            return;
          }

          let raw;
          try {
            raw = JSON.parse(fs.readFileSync(filePath, 'utf-8'));
          } catch (err) {
            core.setFailed(`Failed to load or parse MACHINES.json: ${err.message}`);
            return;
          }

          /**
           * Normalize MACHINES.json into a matrix array with entries:
           *   { selector, kas_file, machine_name }
           * Supports:
           *  - "key": "path.yml"
           *  - "key": { "file_name": "...", "machine_name": "..." }
           *  - "key": [ { "file_name": "...", "machine_name": "..." }, ... ]
           */
          const normalizeEntry = (selector, value) => {
            const out = [];

            const pushItem = (obj) => {
              if (!obj || typeof obj !== 'object') return;
              const kas = obj.file_name;
              const machine = obj.machine_name || selector; // fallback to selector if not provided
              if (!kas || typeof kas !== 'string') return;
              out.push({ selector, kas_file: kas, machine_name: machine });
            };

            if (typeof value === 'string') {
              // Assume machine_name == selector if not specified
              out.push({ selector, kas_file: value, machine_name: selector });
            } else if (Array.isArray(value)) {
              value.forEach(v => pushItem(v));
            } else if (typeof value === 'object' && value) {
              pushItem(value);
            }

            return out;
          };

          // Build final matrix
          let matrix = [];
          for (const [selector, value] of Object.entries(raw)) {
            const items = normalizeEntry(selector, value) || [];
            matrix = matrix.concat(items);
          }

          if (matrix.length === 0) {
            core.setFailed('No entries produced from MACHINES.json after normalization.');
            return;
          }

          // Emit output
          core.setOutput('build_matrix', JSON.stringify(matrix, null, 2));
          console.log('Normalized build matrix:');
          console.log(JSON.stringify(matrix, null, 2));

    - name: Set the build commands
      id: set-build-command
      uses: actions/github-script@v7
      with:
        script: |
          const core = require('@actions/core');

          const flat_build = 'bitbake qcom-multimedia-image';
          core.setOutput('flat_build', flat_build);
          console.log("FLAT BUILD COMMAND:", flat_build);

          const sdk = 'bitbake qcom-multimedia-image && bitbake qcom-multimedia-image -c populate_sdk';
          core.setOutput('sdk_build_command', sdk);
          console.log("SDK BUILD COMMAND:", sdk);

    - name: Update Summary
      shell: bash
      run: |
        echo "## Build Matrix" >> "$GITHUB_STEP_SUMMARY"
        echo "| Selector | Machine Name | KAS File |" >> "$GITHUB_STEP_SUMMARY"
        echo "|---------|--------------|----------|" >> "$GITHUB_STEP_SUMMARY"

        build_matrix='${{ steps.set-matrix.outputs.build_matrix }}'
        # Validate JSON and iterate
        echo "$build_matrix" | jq -c '.[]' | while read -r entry; do
          selector=$(echo "$entry" | jq -r '.selector')
          machine_name=$(echo "$entry" | jq -r '.machine_name')
          kas_file=$(echo "$entry" | jq -r '.kas_file')
          echo "| ${selector} | ${machine_name} | ${kas_file} |" >> "$GITHUB_STEP_SUMMARY"
        done